### ISSUE TITLE
Unityで受信audioを制御したい

### ISSUE THREAD

**Issue by gstecsic** [shiguredo/sora-unity-sdk#1]
Unityアプリケーションで、WebRTCの受信audioだけ音量やパンなどの制御をしたいです。
UnityEngine.AudioSource で audio の downstream が扱えれば理想的です。

**Comment by melpon** [comment]
v0.6.0 で Unity から再生できるようにしました。
サンプルで AudioClip を使ってストリーミング再生しているので確認してみてください。

https://github.com/shiguredo/sora-unity-sdk-samples/blob/2babeb36539c73fd41cc6a7fcd59ee099b9f3ceb/SoraUnitySdkSamples/Assets/SoraSample.cs#L177-L219

（ただ AudioClip のストリーミングだと1秒ぐらい遅延があるみたいなので、リアルタイム性が重要な場合は何か別の方法で再生した方がいいかもしれません）

**Comment by gstecsic** [comment]
実装ありがとうございます。
こちらでためしたところ、やはり現状の実装では、レイテンシーが大きいので、AudioClipを経由せずに、audioBufferに入っているデータをAudioSourceの OnAudioFilterReadで代入させて発音させてみました。この方法で、パンと音量調整もできました。
ありがとうございました。

**Comment by voluntas** [comment]
@gstecsic 確認ありがとうございます！
